export const STR = {
  title: "CROWNWAKE",
  subtitle: "Every fallen army becomes your wake.",
  begin: "BEGIN CONQUEST",
  continue: "CONTINUE",
  howTo: "Click a company, then choose its ground.",
  howToTouch: "Tap a company, then tap its destination.",
  tapToMove: "SELECT A COMPANY",
  map: "FRONTIER",
  closeMap: "RETURN",
  army: "SWARM",
  territory: "TERRITORY",
  objective: "BREAK THE RIVAL CROWN",
  revealed: "FRONTIER REVEALED",
  converted: "THEY RISE FOR YOU",
  retreat: "THE FRONTIER STRIKES BACK",
  victory: "THE WORLD REMEMBERS YOUR COLOUR",
  retry: "PLAY AGAIN",
  audioOn: "SOUND ON",
  audioOff: "SOUND OFF",
  mapHint: "Choose a gold frontier region",
  lockedFortify: "FORTIFICATION — COMING AFTER PROTOTYPE",
  resume: "RESUME",
  reducedMotion: "REDUCED MOTION",
  fullMotion: "FULL MOTION"
  ,battleLocked: "THE BANNERS ARE ENGAGED",
  companies: "COMPANIES",
  yourArmy: "YOUR ARMY",
  companiesHint: "Each group follows its commander. Once a group grows beyond twelve soldiers, divide it into two commands.",
  company: "COMPANY",
  soldiers: "SOLDIERS",
  divide: "DIVIDE",
  groupDivided: "A NEW COMMAND RISES",
  noLivingSoldiers: "NO LIVING SOLDIERS",
  commanderLives: "COMMANDER LIVES",
  chooseGround: "CHOOSE THEIR GROUND",
  blockedGround: "THAT GROUND IS OUT OF RANGE",
    orderCancelled: "ORDER CANCELLED",
    pause: "PAUSE",
  paused: "CONQUEST PAUSED",
  resumeGame: "RESUME"
};
